# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Games-Chess-Referee
version:      0.003
version_from: lib/Games/Chess/Referee.pm
installdirs:  site
requires:
    Games::Chess:                  0.003

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
